# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/liuqin/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/liuqin

PRODUCT_COPY_FILES += 

PRODUCT_PACKAGES += 
